blank_issues_enabled: true
contact_links:
  - name: "ðŸ¤” How to add a model?"
    url: "https://github.com/neuronets/trained-models/blob/master/add_model_instructions.md"
    about: Documentation on how to add a model to the zoo
